return {
    "Also try Deltarune!",
    "Dess wuz here",
    "Also try Deoxynn!",
    "Also try Starrune!",
    "Now with 50% less\nRalsei!",
    "Now with extra\ndarkness!",
    "FUCK YOU, CYBER CITY!!",
    ":]",
    "Hey all! Scott here!",
    "Now with 50% more\nSpamton!",
    "May contain nuts!",
    "More than -1 sold!",
    "It's a game!",
    "Singleplayer!",
    "Keyboard\ncompatible!",
    "Open source!",
    "Not on Steam!",
    "Pixels!",
    "6% bug free!",
    "Absolutely memes!",
    "Indie!",
    "Now in 2D!",
    "[Guaranteed]!",
    "Random splash!",
    "Fear of Anxiety!",
    "SMW forever!",
    "Don't look directly\nat the bugs!",
    "Kinda like Pokemon!",
    "Has an ending\n...planned!",
    "Deja vu!",
    "Deja vu!",
    "Mmmph, mmph!",
    "I have a PR.",
    "Fixing Magical Glass!",
    "LOVE 10 + 1 = 11!",
    "Woah.",
    "Honey, I dug the beans!‌",
    "Home-made!",
    "There's <<a dog\non ,my\nkeyboard!~",
    "RIBBIT!",
    "Potassium",
    "Can You Really Call\nThis Splash Text? I\nDidn't Gain Something\nFrom Reading It\nOr Anything.",
    "Crazy?\nI was crazy once.",
    "All toasters toast\ntoast!",
    "Also try Ribbit!",
    "spring time\nback to school",
    "try to withstand\nthe sun's life-giving\nrays.",
    "sweep a leaf\nsweep away a troubles",
    "cold outside but stay\nwarm inside of you",
    "And in that light,\nI find deliverence",
    "The place that is\nbelieved to be dark",
    "Everything is going\nto be fine",
    "No one is around\nto help",
    "Beep Boop",
    "I've come to make\nan announcement!",
    "There is no crashes\nin Dark Place",
    "I had more splash\nideas but I forgot\nthem",
    "Smile",
    "Oh hi :D",
    "Man I love this clock",
    "Nice Strike!",
    "May include\nDeltarune content",
    "May include bones",
    "May include flesh",
    "Good times only",
    "I found a dog.",
    "I lost the dog.",
    "Why is there\n2 dogs??",
    "Dogs!!",
    "Gangnam Style",
    "Do not ask for advice",
    "Subscribe to\nBikini Spamton",
    "Welcome to the woods",
    "Run this on a\nWii you coward",
    "Right behind you.",
    "Have a break,\nhave a legally distinct\nGitGog",
    "Try FREEWLLY",
    "FRIEND INSIDE ME",
    "VERY, VERY\nINTERESTING",
    "Smells like\nsplash text",
    "human... i remember\nyou're genocides...",
    "Help! They're forcing\nme to make\nsplash texts!",
    "Knockback Bros.\nbut like not\nadvanced",
	"Insert Chapter 7 Side B",
    "Are you feeling GLOOBY?",
    "YOUR TAKING TOO LONG",
    "It's my Jarona!",
    "When you have a bat,\neverything looks \nlike a ball.",
    "Also try Dragon Blazers III!",
    "Cancel my 4am shock therapy.",
	"Sorry to keep\nyou waiting!",
	"Hey guys, I think\nI found a glue!",
    "I LOVE TV!",
    "Same time as 7.",
    "[Proceed]",
    "~Ara ara~",
    "Now with 300%\nmore Mikes!",
    "Enjoy your free\nbattery acid \n(from the pool)",
    "Do re mon. Amen.",
    "Currently swimming OOB...",
    "AREN'T YOU\nFORGETTING SOMETHING\nIMPORTANT?",
	"Splash texts can\nalways be rewritten.\nThat's what\nI believe.",
    "Get your $999,999,999 haircut here!",
    "MAMMA MIA!",
    "Who the hell\nis Mike?!",
    "The field of \nPink and Gold.",
    "Now with platforming!",
    "Protein included",
    "Only one knows \nthe rose's meaning...",
    "The Late Knight Show!",
    "The Late Night Show!",
    "tinnitus",
    "I'll trade my\nrules card for\nyour debit card!",
    "Hold your breath \nand count to 100...",
    "IT'S A MAN'S WORLD",
	"IT'S A SCATMAN'S WORLD",
    "You can never\nwash it all away.\nFuck my fucking \nchud life.",
    "Wavedashing is for casuals!",
    "Was it fun, Kris?",
    "Berdly is NOT an incel!",
    "10 feet 20 the Flour Man... \nis that how it goes?",
    "A REAL [Pipis] Person!",
    "YOUR TOO BRIGHT",
    "Pumkin fall off the wall...",
    "Also try Cat Petterz The RPG!",
    "My sensor cannot detect Bird Boy...",
    "Say it didn't snow.",
    "SAY IT!!!",
    "It was not a dream."
}
